TED/TED/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^$',include('webinfo.urls', namespace='home')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^', include('webinfo.urls', namespace='developer')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TED/webinfo/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views
from .views import (
    DeveloperCreation,
    DeveloperUpdate,
    DeveloperDelete,
    TemplateCreation,
    TemplateUpdate,
    TemplateDelete,
    contact,
    about,
)
urlpatterns = [
    # urls del modelo developer
    url(r'^$', views.principal, name='principal'),
    # url(r'^inicio/',views.inicio, name='inicio'),
    url(r'^Lista/developers/', views.DeveloperList, name='developer_list'),
    url(r'^developer/(?P<pk>[0-9]+)/$',
        views.DeveloperDetail,
        name='developer_detail'),
    url(r'^developer/Nuevo',
        DeveloperCreation.as_view(),
        name="developer_new"),
    url(r'^Editar/(?P<pk>\d+)',
        login_required(DeveloperUpdate.as_view()),
        name='edit'),
    url(r'^Borrar/(?P<pk>\d+)',
        login_required(DeveloperDelete.as_view()),
        name='delete'),

    # urls del modelo templates
    url(r'^Lista/templates/',
        views.TemplateList,
        name='template_list'),
    url(r'^template/(?P<pk>[0-9]+)/$',
        views.TemplateDetail,
        name='template_detail'),
    url(r'^template/Nuevo',
        TemplateCreation.as_view(),
        name="template_new"),
    url(r'^template/Editar/(?P<pk>\d+)',
        login_required(TemplateUpdate.as_view()),
        name='template_edit'),
    url(r'^template/Borrar/(?P<pk>\d+)',
        login_required(TemplateDelete.as_view()),
        name='template_delete'),

    #url de ajax
    url(r'^template/modal_ajax/$', views.ModalAjaxView),

    #urls de la pagina en general
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^about/$', about, name='about'),

]

TED/templates/about.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block head_title %}About{% endblock %}
{% block content %}
<div class="row">
	<div class="col-sm-3 col-xs-12 pull-right">
		<p class="lead text-align-center"><h1>Contact</h1>
		<form method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				{{ form }}
				
				<button type="submit" class="btn btn-primary" style="background-color: black; border-color: black">Send</button>
				
			</form></p>
		</br>
	</div>
	<div class="col-sm-3">
		<p class="lead text-align-center" ><h1>Mision</h1><br>Develop software and web pages that good and innovative designs that meet the specific needs of companies that require our services</br></p>
	</div>
	<div class="col-sm-3">
	<p class="lead text-align-center"><h1>Vision</h1><br>Generate web pages and software of quality that integrate standards for the regulation of the same, as well as generate a friendly trio towards the consumer</p>
	</div>
	<div class="col-sm-3">
	<p class="lead text-align-center"><h1>About Us</h1></br>We are a company that starts its operations in a responsible way with limited resources but that seeks an interpersonal growth of each one of the partners involved in this project</p>
	</div>
</div>
{% endblock %}

TED/templates/base.html
{% load static %}
{% load crispy_forms_tags %}

{% include 'head_css.html' %}

<body>

<!-- NAVBAR
    ================================================== -->


    {% block navbar %}
    {% include 'navbar.html' %}
    {% endblock %}

    <!-- Carousel
    ================================================== -->
    {% include 'carrousel.html' %}


    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->
    {% block content %}

    {% endblock %}

    <!-- FOOTER -->
    <footer class="pie">

      <div class="contenedor">

        <div class="col1">

            <img src="{% static 'img/tedblanco.png' %}" alt="aqui va ted" class="icono_footer">

            <div class="contacto">
                <a href="tel:+5558408520"><i class="fa fa-phone-square" aria-hidden="true"></i><span> (55) 58408520</span></a>
                <a href="tel:+5555480918"><i class="fa fa-phone-square" aria-hidden="true"></i><span> (55) 55480918</span></a>
                <a href="mailto:thisenginersdevelop@gmail.com"><i class="fa fa-envelope-o" aria-hidden="true"></i><span> thisenginersdevelop@gmail.com</span></a>
            </div>

        </div>


        <div class="col2">
            <h4 style="color:white">Pages</h4>
            <ul class="nav">
                <li><a href="{% url 'developer:principal' %}"><i class="fa fa-home" aria-hidden="true"></i> Home</a></li>
                <li><a href="{% url 'developer:about' %}"><i class="fa fa-users" aria-hidden="true"></i> About</a></li>
                <li><a href="{% url 'developer:contact' %}"><i class="fa fa-address-card" aria-hidden="true"></i> Contact</a></li>
                <li><a href="{% url 'developer:developer_list' %}"><i class="fa fa-code" aria-hidden="true"></i> Developers</a></li>
                <li><a href="{% url 'developer:template_list' %}"><i class="fa fa-newspaper-o" aria-hidden="true"></i> Templates</a></li>
            </ul>

            
        </div>

        <div class="col3">

            <p><strong style="color: white;">Siguenos en:</strong></p>
            <div class="redes">
                <div class="face">
                  <a href="http://www.facebook.com/ThisEngineersDevelop/?ref=aymt_homepage_panel" target="_blank"><img alt="Siguenos en Facebook" src="https://lh3.googleusercontent.com/-NSLbC_ztNls/T6VX0g6z8AI/AAAAAAAAA0A/_vyIBrmZbuY/s48/facebook48.png" width=48 height=48 /></a>
              </div>
              <div class="twit">
                <a href="http://twitter.com/AQUI_TU_USUARIO" target="_blank"><img src="https://lh6.googleusercontent.com/-vao9pzZoGtk/T6VYC4d1YMI/AAAAAAAAA0U/4rdP2chJido/s48/twitter48.png" width=48 height=48 alt="Síguenos en Twitter" /></a>
            </div>
            <div class="insta">
                <a href="URL_DE_TU_PERFIL_INSTAGRAM" target="_blank"><img alt="Siguenos en Blogger" src="https://lh3.googleusercontent.com/-D-erW-8vZFo/UIqE3H6oUuI/AAAAAAAABgE/4kh346Lwaxk/s48/instagram48.png" width=48 height=48/></a>
            </div>
        </div>

    </div>

</div>
<p class="pull-right"><a href="#">Back to top</a></p>
<p style="color:white;">&copy; 2016 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
</footer>

{% include 'footer_js.html' %}

TED/templates/carrousel.html
{% load static %}

<div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img class="first-slide img-responsive" src="{% static 'img/teds.png' %}" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>T.E.D</h1>
              <p>Develop software and web pages that good and innovative designs that meet the specific needs of companies that require our services</p>
              <p><a class="btn btn-lg btn-primary" style="background-color: black; border-color: black" 
              href="{% url 'developer:principal' %}" role="button">Home</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="second-slide" src="{% static 'img/code.jpg' %}" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Follow Us</h1>
              <img alt="Siguenos en Facebook" src="https://lh3.googleusercontent.com/-NSLbC_ztNls/T6VX0g6z8AI/AAAAAAAAA0A/_vyIBrmZbuY/s48/facebook48.png" width=48 height=48 /></a>
              <a href="http://twitter.com/AQUI_TU_USUARIO" target="_blank"><img src="https://lh6.googleusercontent.com/-vao9pzZoGtk/T6VYC4d1YMI/AAAAAAAAA0U/4rdP2chJido/s48/twitter48.png" width=48 height=48 alt="Síguenos en Twitter" /></a>
              <a href="URL_DE_TU_PERFIL_INSTAGRAM" target="_blank"><img alt="Siguenos en Blogger" src="https://lh3.googleusercontent.com/-D-erW-8vZFo/UIqE3H6oUuI/AAAAAAAABgE/4kh346Lwaxk/s48/instagram48.png" width=48 height=48/></a>
              <p><a class="btn btn-lg btn-primary" style="background-color: white; border-color: black; color: black" 
              href="{% url 'developer:contact' %}" role="button">Contact</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="third-slide" src="{% static 'img/code2.png' %}" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
             <h1>About Us</h1></br>We are a company that starts its operations in a responsible way with limited resources but that seeks an interpersonal growth of each one of the partners involved in this project</p>
              <p><a class="btn btn-lg btn-primary" style="background-color: white; border-color: black; color: black"  
              href="{% url 'developer:about' %}" role="button">About</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="fa fa-angle-left fa-3x glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="fa fa-angle-right fa-3x glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->

TED/templates/contact.html
	{% extends 'base.html' %}
	{% load staticfiles %}
	{% load bootstrap3 %}
	{% load crispy_forms_tags %}

	{% load i18n %}

	<title>{% block head_title %}Contact{% endblock %}</title>

	{% block content %}
	<div class="row">
		<h1 class="text-align-center">Contact</h1>
		<div class="col-sm-6  col-sm-offset-3">
			<form method="POST" enctype="multipart/form-data" class="lable">
				{% csrf_token %}
				{{ form }}
				{% buttons %}
				<button type="submit" class="btn btn-primary btn-lg" style="background-color: black; border-color: black">Send</button>
				{% endbuttons %}
			</form>
		</div>
	</div>
{% endblock %}  

TED/templates/footer_js.html
{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap3 %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="{% static 'js/holder.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
    <script src ="{% static 'js/busqueda.js' %}"></script>
    <script src = "{% static 'js/jquery.min.js' %}"></script>
    <script src = "{% static 'js/modal.js' %}"></script>
    <script src = "{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript">

        $(".boton").click(function () {    
            var id = $(this).val();
            $.ajax({
                url: '/template/modal_ajax/',
                type: 'GET',
                data: {id: id },

                success: function(datos){
                    console.log(datos)
                    var html="";
                   for(i=0; i<datos.length; i++){
                        html+= '<h1 class="text-align-center titulo-modal">'+datos[i].fields.name+'</h1><hr><img class="img-modal img-responsive" src="/MEDIA/'+datos[i].fields.picture+'" ><p class="desc-modal">'+datos[i].fields.description+'</p><a href="" class="url-modal">'+datos[i].fields.url+'</a>';
                   }
                   $('#datos').html(html);
                }
            });
        });

    </script>
  </body>
</html>

TED/templates/head_css.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Carousel Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Custom styles for this template -->
    <link href="{% static 'css/carousel.css' %}" rel="stylesheet">
    <link href="{% static 'css/estilos.css' %}" rel="stylesheet">
    <link href="{% static 'css/foundation.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/modal.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/busqueda.css' %}">
 
  </head>

  

TED/templates/home.html
{% extends 'base.html' %}
<meta charset="UTF-8">
{% block title %}Inicio{% endblock %}
{% load bootstrap3 %}
{% load i18n %}
{% load static %}

{% block content %}
<div class="container marketing">

  <!-- START THE FEATURETTES -->
  {% for templates in template_list %}
  <div class="row featurette">
    <div class="{{ templates.dtex }}">
      <h2 class="featurette-heading">{{ templates.name }}<span class="text-muted"></span></h2>
      <p class="lead">{{ templates.description }}</p>
    </div>
    <div class="{{ templates.dimg }}">
      <img class="featurette-image img-responsive center-block" src="{{ templates.picture.url }}" alt="Generic placeholder image">
    </div>
  </div>

  <hr class="featurette-divider">
  {% endfor %}


  <!-- Three columns of text below the carousel -->

  <div class="row">


    {% for pr in developer %}
    <div class="col-lg-4 ">
      <img class="img-circle" src="{{ pr.picture.url }}" alt="Generic placeholder image" width="140" height="140">
      <h2>{{ pr.name }}</h2>
      <p>{{ pr.especiality }}</p>
      <div class="dropup">
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Biografia <span class="caret"></span>
        </button>
        <ul class="dropdown-menu biography">
          <li>{{ pr.age }}</li>
          <li>{{ pr.bio }}</li>
          <li>{{ pr.curriculum }}</li>
          <li role="separator" class="divider"></li>
          <li>{{ pr.email }}</li>
        </ul>
      </div>
    </div><!-- /.col-lg-4 -->
    {% endfor %}
  </div><!-- /.row -->


  <!-- /END THE FEATURETTES -->

</div><!-- /.container -->
<br/>
<br/>
<br/>
<br/>

{% endblock %}

TED/templates/inicio.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block head_title %}Store{% endblock %}
{% block jumbotron %}
<div class="jumbotron">
	<div class="container">
		<div class="row">
			<div class="col-sm-6">
				<h1 style="color:white">Store</h1>
				<p style="color:white">Esta es la Tipica tienda que te vende lo que buscas a precios accesibles cerca de tu hogar</p>
					<a class="btn btn-lg btn-success" href="" role="button">Conócenos</a>
				</p>
			</div>

			<div class="col-sm-6"><iframe width="560" height="315" src="https://www.youtube.com/embed/SV7Hg23gF-s" frameborder="0" allowfullscreen></iframe></div>
		</div>
	</div>
</div>
      {% endblock %}
      <!-- <h1>Hello puto mundo</h1> -->
<hr/>
<br/>
{% block content %}
<div class="row">
	<div class="col-sm-3 col-xs-12 pull-right">
		<p class="lead text-align-center">
		<span class="fa-stack fa-lg">
			<i class="fa fa-spinner fa-spin fa-stack-2x"></i>
			<i class="fa fa-whatsapp fa-stack-1x"></i>
		</span></p>
		</br>
	</div>
	<div class="col-sm-3">
		<p class="lead text-align-center">Visión</br><i class="fa fa-code fa-3x" aria-hidden="true"></i></p>
	</div>
	<div class="col-sm-3">
	<p class="lead text-align-center">Misión</p>
	</div>
	<div class="col-sm-3">
	<p class="lead text-align-center">Valores</br><i class="fa fa-spinner fa-spin fa-3x fa-fw"></i></p>
	</div>
</div>
{% endblock %}

TED/templates/navbar.html
{% load static %}

<div class="navbar-wrapper">
  <div class="nav-container container">
    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!-- <a class="navbar-brand icono" href="{% url 'developer:principal' %}"><img class="ted img-responsive" src="{% static 'img/tedblanco.png' %}" alt=""></a> -->

        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'developer:principal' %}"><img class="ted img-responsive" src="{% static 'img/tedblanco.png' %}" alt=""></a></li>
            <li><a href="{% url 'developer:principal' %}"><i class="fa fa-home" aria-hidden="true"></i> Home</a></li>
            <li><a href="{% url 'developer:about' %}"><i class="fa fa-users" aria-hidden="true"></i> About</a></li>
            <li><a href="{% url 'developer:contact' %}"><i class="fa fa-address-card" aria-hidden="true"></i> Contact</a></li>
            <li><a href="{% url 'developer:developer_list' %}"><i class="fa fa-code" aria-hidden="true"></i> Developers</a></li>
            <li><a href="{% url 'developer:template_list' %}"><i class="fa fa-newspaper-o" aria-hidden="true"></i> Templates</a></li>

            <!--li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menu <span class="caret"></span></a>
              <ul class="dropdown-menu">
                    <li class="dropdown-header">Developers</li>
                    <li role="separator" class="divider"></li>
                    <li><a href="{% url 'developer:developer_list' %}">Developer List</a></li>
                    <li><a href="{% url 'developer:developer_new' %}">Add Developer</a></li>
                    <li role="separator" class="divider"></li>
                    <li class="dropdown-header">Templates</li>
                    <li role="separator" class="divider"></li>
                    <li><a href="{% url 'developer:template_list' %}">Template List</a></li>
                    <li><a href="{% url 'developer:template_new' %}">Add Template</a></li>
              </ul>
            </li-->
          </ul>
        </div>
      </div>
    </nav>
  </div>
</div>