TED/TED/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^$',include('webinfo.urls', namespace='home')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^', include('webinfo.urls', namespace='developer')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TED/webinfo/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views
from .views import (
    DeveloperCreation,
    DeveloperUpdate,
    DeveloperDelete,
    TemplateCreation,
    TemplateUpdate,
    TemplateDelete,
    contact,
    about,
)
urlpatterns = [
    # urls del modelo developer
    url(r'^$', views.principal, name='principal'),
    # url(r'^inicio/',views.inicio, name='inicio'),
    url(r'^Lista/developers/', views.DeveloperList, name='developer_list'),
    url(r'^developer/(?P<pk>[0-9]+)/$',
        views.DeveloperDetail,
        name='developer_detail'),
    url(r'^developer/Nuevo',
        DeveloperCreation.as_view(),
        name="developer_new"),
    url(r'^Editar/(?P<pk>\d+)',
        login_required(DeveloperUpdate.as_view()),
        name='edit'),
    url(r'^Borrar/(?P<pk>\d+)',
        login_required(DeveloperDelete.as_view()),
        name='delete'),

    # urls del modelo templates
    url(r'^Lista/templates/',
        views.TemplateList,
        name='template_list'),
    url(r'^template/(?P<pk>[0-9]+)/$',
        views.TemplateDetail,
        name='template_detail'),
    url(r'^template/Nuevo',
        TemplateCreation.as_view(),
        name="template_new"),
    url(r'^template/Editar/(?P<pk>\d+)',
        login_required(TemplateUpdate.as_view()),
        name='template_edit'),
    url(r'^template/Borrar/(?P<pk>\d+)',
        login_required(TemplateDelete.as_view()),
        name='template_delete'),

    #url de ajax
    url(r'^template/modal_ajax/$', views.ModalAjaxView),

    #urls de la pagina en general
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^about/$', about, name='about'),

]

TED/templates/developers/developer_confirm_delete.html
{% extends 'adminlte/base.html' %}
	{% block title %}Eliminar {{ cliente.Razon_Social }}{% endblock %}
	{% block content %}
	{% load bootstrap3 %}
	{% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
<form method="post">{% csrf_token %}
    <h1>¿Estás seguro que deseas borrar el curso "{{ cliente.Razon_Social }}"?</h1>
    <br>
    <input type="submit" value="Borrar" />
</form>
	{% endblock %}

TED/templates/developers/developer_detail.html
{% extends 'base.html' %}
	{% block title %}Detalle del CLiente{% endblock %}
	{% block content %}
	{% load bootstrap3 %}
	{% load staticfiles %}
     <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
	
	<h1>{{ developer.name }}</h1>
	<img src="{{ developer.picture.url }}" alt="Aqui va la foto">
	<h1>{{ developer.age }}</h1>
	<h1>{{ developer.especialty }}</h1>
	<h1>{{ developer.bio }}</h1>
	<h1>{{ developer.curriculum }}</h1>
	<h1>{{ developer.email }}</h1>
	
	{% buttons %}
		<a href="{% url "clientes:edit" cliente.id %}">
			<button type="submit" class="ui-button">{% bootstrap_icon "pencil" %}Editar</button>
		 </a>
		<a href="{% url "clientes:list" %}">
			<button type="submit" class="ui-button">{% bootstrap_icon "arrow-left" %}Regresar</button>
		 </a>
        {% endbuttons %}

{% endblock %}


2017-03-17 15:06

TED/templates/developers/developer_form.html
{% extends 'adminlte/base.html' %}
	{% block title %}Agregar/Editar{% endblock %}
	{% block content %}
	{% load bootstrap3 %}
	{% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
        <h1>Agregar/Editar Cliente</h1>
 <div class="row">
 	<div class="col-sm-6 col-sm-offset-3">
		<form method="post">
	    	{% csrf_token %}
	    	{% bootstrap_form form %}
	    	<input type="submit" value="Agregar/Editar" />
		</form>
	</div>
</div>
{% endblock %}

TED/templates/developers/developer_list.html
{% extends 'base.html' %}
{% block title %}Lista de Desarrolladores{% endblock %}
{% load bootstrap3 %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">

{% block content %}
        {% if developer_list %}
        <h1>Lista de Desarrolladores</h1>
        <table class="table border=1">
            <thead>
                
                    <th>Id</th>
                    <th>Imagen</th>
                    <th>Nombre</th>
                    <th>Edad</th>
                    <th>Especialidad</th>
                    <th>Biografia</th>
                    <th>curriculum</th>
                    <th>E-mail</th>
                    <th>Acciones</th>
                
            </thead>

            <tbody>
            {% for developers in developer_list %}
                <tr>
                    <td align="center" style="vertical-align:middle">{{ developers.id }}</td>
                    <td align="center" style="vertical-align:middle"><img class="img-tabla img-responsive" src="{{ developers.picture.url }}" alt=""></td>
                    <td align="center" style="vertical-align:middle">{{ developers.name }}</td>
                    <td align="center" style="vertical-align:middle">{{ developers.age }}</td>
                    <td align="center" style="vertical-align:middle">{{ developers.especiality }}</td>
                    <td align="center" style="vertical-align:middle">{{ developers.bio }}</td>
                    <td align="center" style="vertical-align:middle">{{ developers.curriculum }}</td>
                    <td align="center" style="vertical-align:middle">{{ developers.email }}</td>

                    <td style="vertical-align:middle">
                    {% buttons %}
                        <a  href="{% url 'developer:developer_detail' developers.id %}"><button type="submit" class="btn btn-primary">{% bootstrap_icon "eye-open" %}Ver</button>
                        </a>

                        <a  href="{% url 'developer:edit' developers.id %}"><button type="submit" class="btn btn-primary">{% bootstrap_icon "eye-open" %}Editar</button>
                        </a>

                        <a href="{% url 'developer:delete' developers.id %}"><button type="submit" class="btn btn-danger">{% bootstrap_icon "erase" %}Borrar</button></a>

                    {% endbuttons %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        {% else %}
            <h1 class="text-align-center">No hay desarrolladores registrados</h1>
        {% endif %}

        <a href="{% url 'developer:developer_new' %}"><button class="btn btn-primary boton">Nuevo Desarrollador</button></a>
{% endblock %}  

TED/templates/developers/new_developer.html
	{% extends 'base.html' %}
	{% load staticfiles %}
	{% load bootstrap3 %}
	{% load i18n %}

	{% block title %}Agregar Cliente{% endblock %}

	{% block content %}
	
  
	
<div class="row">
	<h1 class="text-align-center">Agregar Desarrollador</h1>
	<div class="col-sm-6  col-sm-offset-3">
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
	        {% bootstrap_form form %}
	        {% buttons %}
			 <button type="submit" class="btn btn-primary">{% bootstrap_icon "plus" %}Agregar</button>
	        {% endbuttons %}
		</form>
	</div>
</div>
{% endblock %}  