TED/TED/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^$',include('webinfo.urls', namespace='home')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^', include('webinfo.urls', namespace='developer')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TED/webinfo/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views
from .views import (
    DeveloperCreation,
    DeveloperUpdate,
    DeveloperDelete,
    TemplateCreation,
    TemplateUpdate,
    TemplateDelete,
    contact,
    about,
)
urlpatterns = [
    # urls del modelo developer
    url(r'^$', views.principal, name='principal'),
    # url(r'^inicio/',views.inicio, name='inicio'),
    url(r'^Lista/developers/', views.DeveloperList, name='developer_list'),
    url(r'^developer/(?P<pk>[0-9]+)/$',
        views.DeveloperDetail,
        name='developer_detail'),
    url(r'^developer/Nuevo',
        DeveloperCreation.as_view(),
        name="developer_new"),
    url(r'^Editar/(?P<pk>\d+)',
        login_required(DeveloperUpdate.as_view()),
        name='edit'),
    url(r'^Borrar/(?P<pk>\d+)',
        login_required(DeveloperDelete.as_view()),
        name='delete'),

    # urls del modelo templates
    url(r'^Lista/templates/',
        views.TemplateList,
        name='template_list'),
    url(r'^template/(?P<pk>[0-9]+)/$',
        views.TemplateDetail,
        name='template_detail'),
    url(r'^template/Nuevo',
        TemplateCreation.as_view(),
        name="template_new"),
    url(r'^template/Editar/(?P<pk>\d+)',
        login_required(TemplateUpdate.as_view()),
        name='template_edit'),
    url(r'^template/Borrar/(?P<pk>\d+)',
        login_required(TemplateDelete.as_view()),
        name='template_delete'),

    #url de ajax
    url(r'^template/modal_ajax/$', views.ModalAjaxView),

    #urls de la pagina en general
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^about/$', about, name='about'),

]

TED/templates/template/new_template.html
	{% extends 'base.html' %}
	{% load staticfiles %}
	{% load bootstrap3 %}
	{% load i18n %}

	{% block title %}Agregar Cliente{% endblock %}

{% block content %}
	
<div class="row">
	<div class="col-sm-6 col-sm-offset-3">
		<h1 class="text-align-center">Agregar Template</h1>
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
	        {% bootstrap_form form2 %}
	        {% buttons %}
			 <button type="submit" class="btn btn-primary">{% bootstrap_icon "plus" %}Agregar</button>
	        {% endbuttons %}
		</form>
	</div>
</div>	
{% endblock %}

TED/templates/template/template_list.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}
{% block title %}Lista de Desarrolladores{% endblock %}

{% block content %}

<div class="ventana">
    <div class="modal-body" >
        <a href="#contenido"onclick="closeVentana();"class="cerrar"><h2>&times</h2></a>
        <div id="datos">
            <div>

            </div>
        </div>
    </div>
</div>

{% if request.user.is_superuser %}

<h1 class="cover-heading text-align-center">Lista de Templates</h1>

<center>
    <div class="derecha" id="buscar">
        <input type="search" class="light-table-filter" data-table="order-table" placeholder="Buscar produco">
    </div>
</center>

<br/> 
<div class="container">
    <table class="table table-bordered order-table table-responsive">
        <thead>
            <th class="text-align-center">id</th>
            <th class="text-align-center"> nombre</th>
            <th class="text-align-center"> Descripcion</th>
            <th class="text-align-center"> Imagen</th>
            <th class="text-align-center"> desarrollador</th>
            <th class="text-align-center"> url</th>
            <th>Acciones</th>
        </thead>
    <tbody>
        <tr>
            {% for templates in template_list %}
            <td align="center" style="vertical-align:middle">{{ templates.id }}</td>
            <td align="center" style="vertical-align:middle">{{ templates.name }}</td>
            <td align="center" style="vertical-align:middle">{{ templates.description }}</td>
            <td align="center" style="vertical-align:middle"><p>{{ templates.picture }}</p></td>
            <td align="center" style="vertical-align:middle">{{ templates.developer }}</td>
            <td align="center" style="vertical-align:middle">{{ templates.url }}</td>
            <td>
                {% if request.user.is_superuser %}
                <a href="{% url "developer:template_edit" templates.id %}"><button type="submit" class="btn btn-primary">Editar</button></a>
                <br/>

                <br/>
                <a href="{% url "developer:template_delete" templates.id %}"><button type="submit" class="btn btn-primary">Eliminar</button></a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
    </table>
</div>
{% else %}
<div id="contenido">
    <div class="row column text-center">
        <h2>Ven y conoce nuestras plantillas</h2>
        <hr>
    </div>

    <div class="row small-up-2 large-up-4">
        {% for templates in template_list %}
        <div class="column">
            <img src="{{ templates.picture.url }}" class="img-responsive" />
            <label style="display: none;" class="id_t">{{ templates.id }}</label>
            <h5>{{ templates.name }}</h5>
            <a href="#"><button  class="button expanded boton" onclick="openVentana();" value="{{ templates.id }}">VER DETALLES</button></a>
        </div>
        {% endfor %}
    </div>
</div>
{% endif %}
{% endblock %}